# Generated by Django 4.1.1 on 2022-10-03 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_delete_choice_delete_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
